### ISSUE TITLE
Error validating the office-yeoman generated manifest file

### ISSUE THREAD

**Issue by sumurthy** [OfficeDev/office-addin-validator#10]
I'm just trying to validate the same manifest used in Office yeoman generated project. 
Any idea what could be happening here? 

![image](https://cloud.githubusercontent.com/assets/8384457/26321343/4d12bcea-3edb-11e7-8a6c-e01d36bf30f3.png)

**Comment by MIchaelMainer** [comment]
Sorry for the tardy reply. Do you recall which options you used to generate the manifest?

**Comment by patmill** [comment]
I imagine this is way old now, but...  this just happened to me.  Turned out I had some bad XML encoding in my manifest.  Any chance you tweaked the file (like adding an & for a query string in a URL?)

One feature to add to the validation would be a message stating where the error in the file was.

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
