### ISSUE TITLE
Increase 'resid' character length

### ISSUE THREAD

**Issue by jack-atcipher** [OfficeDev/office-addin-validator#12]
When using 'resid' to define the namespace, I tend to use 'com.example.appname.functionName'; however, the manifest file allows very short character length for 'resid'.  Don't know the reason for such limitation.  It would have been great to expand that to allow more structural naming for variable used in manifest file.

**Comment by MIchaelMainer** [comment]
Thank you for the feedback. @nokafor, can you pass on this feedback?

**Comment by nokafor** [comment]
@MIchaelMainer I passed on the feedback! @LezaMax do you know why the resid is currently restricted? Also, @jack-atcipher do you have an example manifest that shows the structural naming you're going for?

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
