### ISSUE TITLE
Windows line-endings are added

### ISSUE THREAD

**Issue by IanVS** [OfficeDev/office-addin-validator#16]
I'm on a mac, and after running `yo office` to generate a manifest-only project, I tried `yarn validate`, and got `env: node\r: No such file or directory` because of the windows line endings in `/node_modules/.bin/validate-office-addin`.  None of the other files in `node_modules/.bin/` have windows line endings, just that one file.  I'm not familiar enough with the project to figure out how/why that is happening.

**Comment by palla89** [comment]
I solved it using solution posted by user devon on another project (https://github.com/tonistiigi/audiosprite/issues/51):

Steps:
-get node_module path:

`npm config get prefix`

-modify \r\n in cli.js (on mac)

```
cd the_path # the path find in npm config get prefix
brew install dos2unix
dos2unix lib/node_modules/audiosprite/cli.js
```

**Comment by jamesgraham** [comment]
+1

**Comment by jimbol** [comment]
This work-around worked for me, but it's not sustainable. It would be great to have the correct line endings in the repo. Shall I open a PR?

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
