### ISSUE TITLE
Calling validate with no arguments exits silently

### ISSUE THREAD

**Issue by IanVS** [OfficeDev/office-addin-validator#17]
I used `yo office` to generate a manifest-only project, and tried `yarn validate` to check the generated manifest, which (after I fixed line endings, see #16), exited silently, which I assumed meant validation succeeded.  

It turns out that I needed to specify the path to the manifest file to validate, but that wasn't clear to me (I didn't read the [readme](https://github.com/OfficeDev/generator-office#validate-manifestxml) closely enough).  I propose providing a help message to users if they try to run the validator without an argument, letting them know they should specify the path to a manifest file to validate.

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
