### ISSUE TITLE
Should validate-office-addin work with manifest examples?

### ISSUE THREAD

**Issue by fergiemcdowall** [OfficeDev/office-addin-validator#19]
At the moment `validate-office-addin` doesnt seem to work with any of the files on this page: https://dev.office.com/docs/add-ins/overview/add-in-manifests#manifest-v11-xml-file-examples-and-schemas . Should it?

For example: validating "Office Add-in manifest v1.1 example with commands and fallback task pane" gives this error:

```
Calling validation service. This might take a moment...
-------------------------------------
Validation: Failed

Error #1: 
XML Schema Violation: Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests. (link: https://aka.ms/add-in-manifest-schema-violation)
  - Details: The element 'Control' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides' cannot contain text. List of possible elements expected: 'Action' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides'.
  - Line: 78
  - Column: 108
```

**Comment by fergiemcdowall** [comment]
The validator seems to take into account the order that xml elements appear in. If I move <AppDomains> underneath (but at the same level as) <IconUrl> then things work.

**Comment by Rick-Kirkham** [comment]
It is a common practice for XSDs to require child elements in a certain order. So, I think the validator is fine. But it sounds like one or more of our examples in the file you linked to has things in the wrong order. Please raise this as an issue in the repo [office-js-docs](https://github.com/OfficeDev/office-js-docs/issues). Be sure to specify the article title (or URL) and specify exactly which example is wrong and which element you had to reposition. Thanks.

**Comment by Rick-Kirkham** [comment]
I have created a bug to get the documentation fixed: https://github.com/OfficeDev/office-js-docs/issues/1228

**Comment by fergiemcdowall** [comment]
👍👍

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
