### ISSUE TITLE
Sync Github Releases with npm releases

### ISSUE THREAD

**Issue by TheSamsterZA** [OfficeDev/office-addin-validator#21]
Hi,

I had opened #9 a few months ago and periodically checked [the Releases page on Github](https://github.com/OfficeDev/office-addin-validator/releases) to see if a new version was released that [contained the fix for it](https://github.com/OfficeDev/office-addin-validator/pull/15) (thanks @gesiu!).

Today, I updated my node packages and [noticed the version bump to 1.0.5](https://www.npmjs.com/package/office-addin-validator), which indeed fixed the above-mentioned issue.

However, the Releases page on Github only lists versions up to 1.0.2.

Please fix this so that Github releases are synced with npm releases.

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
