### ISSUE TITLE
Validator gives bad error messages when elements are out of order for an XSD sequence

### ISSUE THREAD

**Issue by GoodmanEScott** [OfficeDev/office-addin-validator#22]
The validator returns confusing error messages when elements are not in the order required by the XSD sequence.

**Steps to reproduce**
1. Download the a test manifest from 
https://github.com/OfficeDev/outlook-add-in-command-demo/blob/master/command-demo-manifest.xml

2. Run the validator against this file

(You'll receive an error about SupportUrl element missing) 

3. Add the SupportUrl element to the test manifest just above the HighResolutionIconUrl element and run the validator again

(You'll receive an error message about HighResolutionIconUrl not valid)

4. Delete the HighResolutionIconUrl element and run the validator again

(You'll receive an error message about HighResolutionIconUrl being required)

5. Add the HighResolutionIconUrl element just above the SupportUrl element and run the validator again.

(Validation will pass)

**Expected Results**
The validator should tell me the truth about the problem - SupportUrl and HighResolutionIconUrl are both valid, but one needs to follow the other.  Instead it tell me that HighResolutionIconUrl is not valid which is a completely different message.

Schema here: https://msdn.microsoft.com/en-us/library/dn585105(v=office.12).aspx

GIF of issue here: https://imgur.com/a/raF7QVA

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
