### ISSUE TITLE
Validator responds with ".. not contain a valid XML document..." if <DefaultLocale> contains an invalid value 

### ISSUE THREAD

**Issue by codebear** [OfficeDev/office-addin-validator#25]
If you take `valid_outlook.xml` from https://github.com/OfficeDev/office-addin-validator/blob/master/manifest-to-test/valid_outlook.xml and change `<DefaultLocale>` from `en-US` to `en-EN` you get the following.
```
$ validate-office-addin valid_outlook.xml
Calling validation service. This might take a moment...
-------------------------------------
Validation: Failed
  Error Code: 400
  Error(s):
  Request body does not contain a valid XML document, and/or is too large (capped at 256kb).
-------------------------------------
```

Expected result:
An error message explaining that `<DefaultLocale>` does not contain a valid value.

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
