### ISSUE TITLE
Suggestion: Check resids and resource type

### ISSUE THREAD

**Issue by MakotoE** [OfficeDev/office-addin-validator#26]
The validator (1.0.5) returns passing status if a manifest includes incorrect resid or incorrect resource type. Trying to upload a manifest file which has these errors will cause Office to throw an error.

Example of incorrect resid:

```
<Title resid="abc"/> <!-- Wrong resid value -->
...
<bt:String id="abd" DefaultValue="text" />
```

Example of incorrect resource type:

```
<GetStarted>
    <Title resid="Title"/>
</GetStarted>
...
<Resources>
    <bt:LongStrings>
        <bt:String id="Title" DefaultValue="Title" /> <!-- Should be a ShortString -->
    </bt:LongStrings>
</Resources>
```

It would greatly aid developers if the addin validator returned an error with an appropriate error message if the manifest file being scanned contains any of these errors.

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
