### ISSUE TITLE
"Validation: Failed" should throw error

### ISSUE THREAD

**Issue by shirbr510** [OfficeDev/office-addin-validator#27]
I'm trying to create a CI flow revolving around manifest validation.

A validation is technically a test.
therefore, I expect that a failed validation will fail the same way that tests do.

installed package version: 1.0.5
node version: v11.13.0
OS: Mac OSX 10.14.3

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
