### ISSUE TITLE
Issues with <SupportUrl> validation

### ISSUE THREAD

**Issue by misaunde** [OfficeDev/office-addin-validator#28]
I have a 750 line manifest file and it took me a while to narrow down what was causing my file to fail validation.

This line turned out to be the problem:

        <SupportUrl DefaultValue="[Insert the URL of a page that provides support information for the app]" />

Which yielded this ambiguous error message about my file:
![image](https://user-images.githubusercontent.com/10051350/56438834-76914780-62a1-11e9-8526-1d910ac7af4a.png)

I have a large xml file and this gave me no clue where to start. Also, what made it harder to figure out that that line was my problem, was that it inconsistently flags that line as being valid or invalid against different manifest files I ran!

Example where the line `DefaultValue="[Insert the URL of a page that provides support information for the app]"` is valid:
Run the manifest with id=e504fb41-a92a-4526-b101-542f357b7acb here:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1 

Example where it fails:
https://github.com/OfficeDev/Office-Add-in-Commands-Samples/blob/master/Excel/Manifest/ExcelAddinWithCommandsOnDataTab.xml

Should this be more consistent? At the very least, could you output a line number or anything else for reference that would be helpful to indicate what triggered the error or where the xml isn't valid? 

Eventually I was able to fix this issue by including the most valid support url I could think of:

    <SupportUrl DefaultValue="https://google.com" />

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
