### ISSUE TITLE
Trailing URI Spaces

### ISSUE THREAD

**Issue by mlafleur** [OfficeDev/office-addin-validator#7]
There is a issue with trailing spaces in URIs on certain Outlook clients (iOS for example). If there is a trailing space, Outlook will fail attempting to parse the URI. Currently the validator is accepting these trailing spaces. I've not tested extensively but it seems reasonable that this may be the case with other Office hosts as well (assuming the same parser is used across hosts). 

Given that this is calling the backend validator, it clearly should be resolved at the service level. That said, it may be worth considering adding a local test until the service itself can be updated. .

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
