### ISSUE TITLE
Validator hangs on invalid local manifest file path

### ISSUE THREAD

**Issue by TheSamsterZA** [OfficeDev/office-addin-validator#9]
**Environment: Windows**

NOTE: running the following directly from the Command Prompt works:

    C:\node_modules\.bin>validate-office-addin C:\test.xml
    -------------------------------------
    Error: Please provide a valid local manifest file path.
    -------------------------------------

    C:\node_modules\.bin>

I now want to run this as an npm script defined in my package.json:

    "scripts": {
      "validate-manifest": "validate-office-addin <path-to-manifest-file>"
    }

This is run with the command: `npm run validate-manifest`.

When the file does not exist, this correctly shows the error message, BUT the node process hangs instead of exiting.

Please fix.

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention.

**Comment by TheSamsterZA** [comment]
Fixed in https://github.com/OfficeDev/office-addin-validator/commit/2c07c25ea18a7860c7836879a9741f6a2cad53c4 (version 1.0.5)
